config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :configs, only: %i[new create show] do
    resources :projects, only: %i[index show] do
      member do
        get :members_preview
        get :merge_requests_size
      end

      get :projects_list, on: :collection

      resources :members, only: %i[index show]
    end
  end
end

app/models/application_record.rb
# typed: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/config.rb
# typed: strict

class Config < ApplicationRecord
  extend T::Sig

  encrypts :token
  encrypts :domain

  validates :token, presence: true
  validates :domain, presence: true

  sig { returns(Api::Client) }
  def api_client
    Api::Client.new(token:, domain:)
  end
end

app/controllers/application_controller.rb
# typed: strict

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/configs_controller.rb
# typed: strict

class ConfigsController < ApplicationController
  extend T::Sig

  sig { void }
  def show
    config = Config.find(params[:id])

    respond_to do |f|
      f.html { render :show, locals: { config: } }
    end
  end
end

app/controllers/members_controller.rb
# typed: strict

class MembersController < ApplicationController
  extend T::Sig

  sig { void }
  def index
    config = Config.find(params[:config_id])

    page = params[:page] || 1
    client = config.api_client
    response = client.get("api/v4/projects/#{params[:project_id]}/members/all", page:)

    if response.success?
      members = Members::MemberParser.parse(response.body)
      pagination = Common::Pagination.new(response.raw)

      respond_to do |f|
        f.html { render :index, locals: { members:, pagination:, config: } }
      end
    else
      # handle bad response
    end
  end
end

app/controllers/projects_controller.rb
# typed: strict

class ProjectsController < ApplicationController
  extend T::Sig

  sig { void }
  def index
    config = find_config

    respond_to do |f|
      f.html { render :index, locals: { config: } }
    end
  end

  sig { void }
  def projects_list
    config = find_config
    client = config.api_client

    response = client.get("api/v4/projects",
      simple: true, # Returns only limited fields for each project
      page: params[:page],
      search: params[:search],
      order_by: "name",
      per_page: 24,
      sort: "asc",
    )

    if response.success?
      projects = Projects::ProjectParser.parse(response.body)
      pagination = Common::Pagination.new(response.raw)

      respond_to do |f|
        f.html { render :projects_list, locals: { projects:, pagination:, config: } }
      end
    else
      # handle bad response
    end
  end

  sig { void }
  def members_preview
    config = find_config
    client = config.api_client

    response = client.get("api/v4/projects/#{params[:id]}/members/all",
      page: 1,
      per_page: 8,
    )

    if response.success?
      members = Members::MemberParser.parse(response.body)

      respond_to do |f|
        f.html { render :members_preview, locals: { members: } }
      end
    else
      # handle bad response
    end
  end

  sig { void }
  def merge_requests_size
    config = find_config
    client = config.api_client

    response = client.get("api/v4/projects/#{params[:id]}/merge_requests",
      page: 1,
      per_page: 1,
    )

    if response.success?
      merge_requests_size = response.raw["X-Total"]&.to_i

      respond_to do |f|
        f.html { render :merge_requests_size, locals: { merge_requests_size: } }
      end
    else
      # handle bad response
    end
  end

  sig { void }
  def show
    config = find_config
    client = config.api_client

    response = client.get("api/v4/projects/#{params[:id]}")

    if response.success?
      project = Projects::ProjectParser.parse(response.body)

      respond_to do |f|
        f.html { render :show, locals: { project:, config: } }
      end
    else
      # handle bad response
    end
  end

  private

  sig { returns(Config) }
  def find_config
    Config.find(params[:config_id])
  end
end

app/helpers/application_helper.rb
# typed: strict

module ApplicationHelper
end

app/views/configs/show.html.erb
<div>
  <%= config.token %>
</div>
<div>
  <%= config.domain %>
</div>

<%= link_to "Projects", config_projects_path(config) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gitlab Statistics" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="main">
    <header class="header">
      <div class="header-title-container">
        <h1 class="header-title">GitLab</h1>
        <span class="header-separator">|</span>
        <span class="header-logo">
          <%= image_tag "header-logo.svg", class: "header-logo" %>
        </span>
      </div>
    </header>

    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/members/index.html.erb
<% members.each do |member| %>
  <div><%= member.name %></div>
  <img src="<%= member.avatar_url %>" alt="<%= member.name %>">
<% end %>

<div>
  <% if pagination.prev_page %>
    <%= link_to pagination.prev_page, config_project_members_path(config, params[:project_id], page: pagination.prev_page) %>
  <% end %>

  <% if pagination.next_page %>
    <%= link_to pagination.next_page, config_project_members_path(config, params[:project_id], page: pagination.next_page) %>
  <% end %>
</div>

app/views/projects/index.html.erb
<%= form_with url: config_projects_path(config), method: :get do |f| %>
  <div class="search-input-container">
    <%= f.text_field :search,
      value: params[:search],
      autocomplete: "off",
      inputmode: "search",
      type: "search",
      placeholder: "Search projects by name or description...",
      class: "search-input" %>
    <%= f.submit "Search", class: "search-input-button" %>
  </div>
<% end %>

<%= turbo_frame_tag :projects_list, src: projects_list_config_projects_path(config, page: params[:page], search: params[:search]), loading: :lazy do %>
  <div class="centered">
    <%= render "shared/loading_spinner" %>
  </div>
<% end %>

app/views/projects/members_preview.html.erb
<%= turbo_frame_tag :members_preview do %>
  <% members.each do |member| %>
    <%= tag.img(
      class: "members-preview-avatar",
      src: member.avatar_url,
      alt: member.name,
      title: member.name
    ) %>
  <% end %>
<% end %>

app/views/projects/merge_requests_size.html.erb
<%= turbo_frame_tag :merge_requests_size do %>
  <%= merge_requests_size %>
<% end %>

app/views/projects/projects_list.html.erb
<%= turbo_frame_tag :projects_list do %>
  <div class="project-list">
    <% if projects.any? %>
      <% projects.each do |project| %>
        <div class="project-item">
          <div class="project-item-name-container">
            <p title="<%= project.name %>" class="project-item-name">
              <%= project.name %>
            </p>
            <p title="<%= project.description %>" class="project-item-description">
              <%= project.description %>
            </p>
          </div>
          <span class="project-item-separator">|</span>
          <%= link_to "GitLab link", project.web_url, class: "project-item-link", target: "_blank" %>
          <span class="project-item-separator">|</span>
          <%= link_to "Stats", config_project_path(config, project.id), class: "project-item-link", data: { turbo_frame: :_top } %>
        </div>
      <% end %>
    <% else %>
      <div class="centered">
        <%= render "shared/no_data" %>
      </div>
    <% end %>
  </div>

  <% if pagination.next_page || pagination.current_page != 1 %>
    <div class="pagination-container">
      <% if pagination.first_page && pagination.first_page != pagination.prev_page && pagination.first_page != pagination.current_page %>
        <%= link_to pagination.first_page, config_projects_path(config, page: pagination.first_page), class: "pagination-link", data: { turbo_frame: :_top } %>
      <% end %>

      <% if pagination.prev_page && pagination.prev_page - 1 > pagination.first_page %>
        <p>...</p>
      <% end %>

      <% if pagination.prev_page %>
        <%= link_to pagination.prev_page, config_projects_path(config, page: pagination.prev_page), class: "pagination-link", data: { turbo_frame: :_top } %>
      <% end %>

      <p class="pagination-current-page">
        <%= pagination.current_page %>
      </p>

      <% if pagination.next_page %>
        <%= link_to pagination.next_page, config_projects_path(config, page: pagination.next_page), class: "pagination-link", data: { turbo_frame: :_top } %>
      <% end %>

      <% if pagination.next_page && pagination.last_page && pagination.next_page + 1 < pagination.last_page %>
        <p>...</p>
      <% end %>

      <% if pagination.last_page && pagination.last_page != pagination.next_page && pagination.last_page != pagination.current_page %>
        <%= link_to pagination.last_page, config_projects_path(config, page: pagination.last_page), class: "pagination-link", data: { turbo_frame: :_top } %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/projects/show.html.erb
<div class="project-container">
  <div class="project-members-card">
    <div class="project-members-header-container">
      <p class="project-members-header">members</p>
      <%= link_to "see all", config_project_members_path(config, project.id), class: "members-preview-view-all", data: {turbo_frame: :_top} %>
    </div>

    <%= turbo_frame_tag :members_preview, class: "project-members-gird", src: members_preview_config_project_path(config, project.id), loading: :lazy do %>
      <%= render "shared/loading_spinner" %>
    <% end %>
  </div>

  <div class="project-general-info-card">
    <p class="project-general-info-header">general info</p>

    <div class="project-general-info-grid">
      <% if (owner = project.owner) %>
        <p class="project-general-info-grid-title">owner:</p>
        <div class="image-with-text">
          <%= tag.img src: owner.avatar_url, alt: owner.name %>
          <p><%= owner.name %></p>
        </div>
      <% end %>

      <p class="project-general-info-grid-title">name:</p>
      <p><%= project.name %></p>

      <p class="project-general-info-grid-title">description:</p>
      <p><%= project.description.presence || "-" %></p>

      <p class="project-general-info-grid-title">created at:</p>
      <p><%= project.created_at || "-" %></p>

      <p class="project-general-info-grid-title">updated at:</p>
      <p><%= project.updated_at || "-" %></p>

    </div>
  </div>
</div>

<%= turbo_frame_tag :merge_requests_size, src: merge_requests_size_config_project_path(config, project.id), loading: :lazy do %>
  <%= render "shared/loading_spinner" %>
<% end %>

app/views/shared/_loading_spinner.html.erb
<span class="loading-spinner"></span>

app/views/shared/_no_data.html.erb
<div class="no-data-container">
  <%= image_tag "no-data-icon.svg", class: "no-data-icon" %>
  <span class="no-data-text">nothing to show</span>
</div>